name: Deploy Release

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader
      - name: Build project
        run: php artisan build
      - name: Get last release
        uses: actions/github-script@v4
        with:
          script: |
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1,
            });
            console.log(releases[0].tag_name);
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_last_release.outputs.result.replace(/(\d+)$/, (_, num) => parseInt(num) + 1) }}
          release_name: Release ${{ steps.get_last_release.outputs.result.replace(/(\d+)$/, (_, num) => parseInt(num) + 1) }}
          body: |
            This is an automated release created by GitHub Actions.
          draft: false
          prerelease: false
      - name: Deploy release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/release.zip
          asset_name: release.zip
          asset_content_type: application/zip
